#!/bin/bash
set -eux  # fail fast and show commands

echo "Testing if k3d is installed..."
python -c "import k3d; print('k3d is available')"

jupyter nbextension install --py --user k3d
jupyter nbextension enable --py --user k3d
