#!/bin/bash
set -eux  # Enable detailed output and fail on error

echo "Running postBuild script"

# Check if k3d is installed
python -c "import k3d; print('k3d is installed')"

# Install and enable k3d extension
echo "Installing k3d extension"
jupyter nbextension install --py --sys-prefix k3d
echo "Enabling k3d extension"
jupyter nbextension enable --py --sys-prefix k3d

echo "postBuild script completed successfully"
